name: e-commerce-subscriber-service
services:
  e-commerce-subscriber-service:
    build:
      context: .
    container_name: e-commerce-subscriber-service
    env_file:
      - ./.env
    ports:
      - ${PORT}:${PORT}
    networks:
      - e-commerce-network
networks:
  e-commerce-network:
    external: true
