services:
  e-commerce-subscriber-service:
    build:
      context: .
    container_name: e-commerce-subscriber-service
    env_file:
      - ./.env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - rabbitmq
      - mongo
  rabbitmq:
    env_file:
      - ./.env
    image: rabbitmq:3-alpine
    container_name: e-commerce-subscriber-rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_PASS}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  mongo:
    env_file:
      - ./.env
    image: mongo:latest
    container_name: e-commerce-subscriber-mongo
    hostname: mongo
    ports:
      - 27017:27017
    volumes:
      - subscriber-data:/data

volumes:
  rabbitmq-data:
  subscriber-data:
